
all: python-test

python-test: test-heaps

test-heaps: test-heap test-leftist

test-heap:
	python heap.py

test-leftist:
	python leftist_heap.py

.PHONY: all python-test test-heaps test-heap test-leftist
